<?php

/**
 * @file
 * Provides multiple plugins for the Restaurant Distribution
 */

include_once 'restaurant_plugins.theme.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */ 
function restaurant_plugins_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/**
 * Implements hook_preprocess_panels_ipe_pane_wrapper().
 */
function restaurant_plugins_preprocess_panels_ipe_pane_wrapper(&$vars) {
  $pane = $vars['pane'];
  $display = $vars['display'];
  $renderer = $vars['renderer'];

  if (user_access('administer advanced pane settings')) {
    $css_link = array(
      'title' => t('CSS'),
      'href' => $renderer->get_url('pane-css', $pane->pid),
      'attributes' => array(
        'class' => array('ctools-use-modal', 'pane-css'),
        'title' => t('CSS'),
      ),
    );

    // Make sure css is added just after style.
    $style_link_key = array_search('style', array_keys($vars['links']));
    $links_start = array_slice($vars['links'], 0, $style_link_key + 1);
    $links_end = array_slice($vars['links'], $style_link_key);

    // Add css link
    $links_start['css'] = $css_link;
    $vars['links'] = array_merge($links_start, $links_end);
  }
}


