<?php
/**
 * @file
 * Provides base configuration and structure for the Restaurant Distribution
 */

include_once 'restaurant_base.features.inc';

/**
 * Implements hook_panopoly_config_info()
 */
function restaurant_base_panopoly_config_info() {
  $info = array();

  // General
  $info['general'] = array(
    'title' => t('General'),
    'description' => t('General settings such as site name, site mail.'),
    'weight' => 10,
    'config' => array(
      'site_name' => array(
        'title' => t('Site name'),
        'type' => 'string',
        'default' => variable_get('site_name', 'Restaurant'),
      ),
      'site_mail' => array(
        'title' => t('Site mail'),
        'description' => t('The From address in automated e-mails sent during registration and new password requests, and other notifications. (Use an address ending in your site\'s domain to help prevent this e-mail being flagged as spam.)'),
        'type' => 'string',
        'default' => variable_get('site_mail'),
      ),
    ),
  );

  // Contact.
  $info['contact'] = array(
    'title' => t('Contact'),
    'description' => t('Contact and opening hours.'),
    'weight' => 20,
    'config' => array(
      'phone' => array(
        'title' => t('Phone'),
        'type' => 'string',
        'description' => t('Phone number for restaurant.'),
        'show_on_install' => TRUE,
      ),
      'address' => array(
        'title' => t('Address'),
        'type' => 'text',
        'description' => t('Restaurant address.'),
        'show_on_install' => TRUE,
      ),
      'opening_hours' => array(
        'title' => t('Opening Hours'),
        'type' => 'text',
        'description' => t('Restaurant opening hours.'),
        'show_on_install' => TRUE,
      ),
    ),
  );

  // Services.
  $info['services'] = array(
    'title' => t('Services'),
    'description' => t('Settings for external web services such as Google analytics, Disqus..etc'),
    'weight' => 30,
    'config' => array(
      'googleanalytics_account' => array(
        'title' => t('Google analytics ID'),
        'description' => t('Google analytics ID in the form of UA-xxxxxxx-yy. !link for advanced settings.', array(
          '!link' => l(t('Click here'), 'admin/config/system/googleanalytics'),
        )),
        'type' => 'string',
      ),
    ),
  );

  // Social.
  $info['social'] = array(
    'title' => t('Social'),
    'description' => t('Settings for social networks such as Twitter, Facebook..etc'),
    'weight' => 40,
  );
  $networks = restaurant_base_get_social_networks();
  foreach ($networks as $name => $network) {
    $info['social']['config'][$name] = array(
      'title' => $network['title'],
      'type' => 'string',
      'show_on_install' => TRUE,
    );  
  }

  return $info;
}

/**
 * Returns a list of social networks available.
 */
function restaurant_base_get_social_networks() {
  $networks = array(
    'twitter' => array(
      'title' => t('Twitter'),
      'button_text' => t('Follow us on Twitter'),
    ),
    'facebook' => array(
      'title' => t('Facebook'),
      'button_text' => t('Like us on Facebook'),
    ),
    'google_plus' => array(
      'title' => t('Google+'),
      'button_text' => t('Follow us on Google+'),
    ),
    'yelp' => array(
      'title' => t('Yelp'),
      'button_text' => t('Find us on Yelp'),
    ),
  );

  // Add value to networks.
  foreach ($networks as $name => $network) {
    $networks[$name]['default'] = panopoly_config_get($name);
  }

  return $networks;
}
