<?php

/**
 * @file
 * Installation file for Restaurant Location Demo
 */


/**
 * Implements hook_enable().
 */
function restaurant_location_demo_enable() {
  _panopoly_core_import_demo_content(array_keys(restaurant_location_get_migrations()));
}

/**
 * Implements hook_disable().
 */
function restaurant_location_demo_disable() {
  _panopoly_core_rollback_demo_content(array_keys(restaurant_location_get_migrations()));
}
