<?php

/**
 * @file
 * Installation file for Restaurant Event Demo
 */


/**
 * Implements hook_enable().
 */
function restaurant_event_demo_enable() {
  _panopoly_core_import_demo_content(array_keys(restaurant_event_get_migrations()));
}

/**
 * Implements hook_disable().
 */
function restaurant_event_demo_disable() {
  _panopoly_core_rollback_demo_content(array_keys(restaurant_event_get_migrations()));
}
