<?php
/**
 * @file
 * Code for the Restaurant Menu feature.
 */

include_once 'restaurant_menu.features.inc';

/**
 * Implements hook_menu().
 */
function restaurant_menu_menu() {

  $items['admin/menus/add'] = array(
    'title' => 'Add menu',
    'weight' => 10,
    'page callback' => 'restaurant_menu_add_menu_admin',
    'access arguments' => array('administer menus'),
    'file' => 'restaurant_menu.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/menus/manage'] = array(
    'title' => 'Manage menus',
    'weight' => 20,
    'page callback' => 'restaurant_menu_manage_menus_admin',
    'access arguments' => array('administer menus'),
    'file' => 'restaurant_menu.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

//  $items['admin/menus/categories'] = array(
//    'title' => 'Menu categories',
//    'weight' => 30,
//    'access arguments' => array('administer menus'),
//    'page callback' => 'restaurant_menu_menu_categories_admin',
//    'file' => 'restaurant_menu.admin.inc',
//    'type' => MENU_LOCAL_TASK,
//  );

  $items['admin/menus/categories/add'] = array(
    'title' => 'Add category',
    'page callback' => 'restaurant_menu_add_menu_category_admin',
    'access arguments' => array('administer menus'),
    'file' => 'restaurant_menu.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function restaurant_menu_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  // Add action link to 'admin/menus/add' on 'admin/menus' page.
  if (drupal_match_path($root_path, "admin/menus\nadmin/menus/*")) {
    $item = menu_get_item('admin/menus/add');
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }

    $item = menu_get_item('admin/menus/categories/add');
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }
}

/**
 * Implements hook_permission().
 */
function restaurant_menu_permission() {
  return array(
    'administer menus' => array(
      'title' => t('Administer Menus'),
      'description' => t('Access the menu admininstration pages and manage menus.'),
    ),
  );
}

/**
 * Implements hook_preprocess().
 */
function restaurant_menu_preprocess_views_view_table(&$variables) {
  $view = $variables['view'];
  if ($view->name == 'administration_menus') {
    // Add css.
    drupal_add_css(drupal_get_path('module', 'restaurant_menu') . '/css/restaurant_menu.css');
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function restaurant_menu_form_menu_node_form_alter(&$form, &$form_state, $form_id) {
  $language = $form['language']['#value'];

  // Hide locations field if restaurant_location module is disabled.
  if (!module_exists('restaurant_location')) {
    $form['field_menu_locations']['#access'] = FALSE;
  }
  // Else show a message if no locations has been created.
  else if (empty($form['field_menu_locations'][$language]['#options'])) {
    $form['field_menu_locations'][$language]['#access'] = FALSE;
    $form['field_menu_locations']['message'] = array(
      '#markup' => t('You have not created any locations. The default location is being used.'),
    );
  }
}

/**
 * Implements hook_default_page_manager_pages_alter().
 */
function restaurant_menu_default_page_manager_pages_alter(&$pages) {
  // Remove pane if location is not enabled.
  if (isset($pages['menus'])) {
    if (!module_exists('restaurant_location')) {
      if (!empty($pages['menus']->default_handlers['page_menus_panel_context']->conf['display']->content['new-2'])) {
        $pane_new_2 = $pages['menus']->default_handlers['page_menus_panel_context']->conf['display']->content['new-2'];
        if ($pane_new_2->subtype == 'location_browse_menus_link') {
          unset($pages['menus']->default_handlers['page_menus_panel_context']->conf['display']->content['new-2']);
        }
      }
    }
  }
}
