<?php
/**
 * @file
 * Code for the Restaurant Location feature.
 */

include_once 'restaurant_location.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function restaurant_location_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/**
 * Implements hook_menu().
 */
function restaurant_location_menu() {

  $items['admin/locations/manage'] = array(
    'title' => 'Manage locations',
    'weight' => 10,
    'page callback' => 'restaurant_location_manage_locations_admin',
    'access arguments' => array('administer locations'),
    'file' => 'restaurant_location.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/locations/add'] = array(
    'title' => 'Add location',
    'weight' => 20,
    'page callback' => 'restaurant_location_add_location_admin',
    'access arguments' => array('administer locations'),
    'file' => 'restaurant_location.admin.inc',
    'type' => MENU_LOCAL_ACTION,
  );

  return $items;
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function restaurant_location_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  // Add action link to 'admin/locations/add' on 'admin/locations' page.
  $items = array(
    'actions' => array(
      'admin/locations/add',
    ),
    'tabs' => array(
      'admin/locations/add',
      'admin/locations',
    ),
  );

  $new_data = restaurant_admin_show_menu_items_for_paths_pattern($items, $root_path, "admin/locations\nadmin/locations/*");
  if (count($new_data)) {
    $data = $new_data;
  }
}

/**
 * Implements hook_permission().
 */
function restaurant_location_permission() {
  return array(
    'administer locations' => array(
      'title' => t('Administer Locations'),
      'description' => t('Access the location admininstration pages and manage locations.'),
    ),
  );
}

/**
 * Helper function to get an array of locations.
 */
function restaurant_location_get_locations() {
  return db_select('node', 'n')
    ->condition('type', 'location')
    ->fields('n', array('nid'))
    ->execute()
    ->fetchCol(0);
}

/**
 * Implements hook_migrate_api().
 */
function restaurant_location_migrate_api() {
  return array(
    'api' => 2,
    'groups' => array(
      'restaurant_location_demo' => array(
        'title' => t('Restaurant Location demo content'),
      ),
    ),
    'migrations' => restaurant_location_get_migrations(),
  );
}

/**
 * Returns an array of migrations.
 */
function restaurant_location_get_migrations() {
  return array(
    'RestaurantLocationMigrateLocationMigration' => array(
      'class_name' => 'RestaurantLocationMigrateLocationMigration',
      'group_name' => 'restaurant_location_demo',
    ),
    'RestaurantLocationMigrateSlideshowMigration' => array(
      'class_name' => 'RestaurantLocationMigrateSlideshowMigration',
      'group_name' => 'restaurant_location_demo',
    ),
    'RestaurantLocationMigrateSlideMigration' => array(
      'class_name' => 'RestaurantLocationMigrateSlideMigration',
      'group_name' => 'restaurant_location_demo',
    ),
    'RestaurantLocationMigrateTextMigration' => array(
      'class_name' => 'RestaurantLocationMigrateTextMigration',
      'group_name' => 'restaurant_location_demo',
    ),
  );
}
