<?php
/**
 * @file
 * Code for the Restaurant Location feature.
 */

include_once 'restaurant_location.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function restaurant_location_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/**
 * Implements hook_menu().
 */
function restaurant_location_menu() {

  $items['admin/locations/add'] = array(
    'title' => 'Add location',
    'weight' => 10,
    'page callback' => 'restaurant_location_add_location_admin',
    'access arguments' => array('administer locations'),
    'file' => 'restaurant_location.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/locations/manage'] = array(
    'title' => 'Manage locations',
    'weight' => 20,
    'page callback' => 'restaurant_location_manage_locations_admin',
    'access arguments' => array('administer locations'),
    'file' => 'restaurant_location.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function restaurant_location_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  // Add action link to 'admin/locations/add' on 'admin/locations' page.
  if (drupal_match_path($root_path, "admin/locations")) {
    $item = menu_get_item('admin/locations/add');
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }
}

/**
 * Implements hook_permission().
 */
function restaurant_location_permission() {
  return array(
    'administer locations' => array(
      'title' => t('Administer Locations'),
      'description' => t('Access the location admininstration pages and manage locations.'),
    ),
  );
}
