<?php

/**
 * @file
 * Installation file for Restaurant Demo.
 */

/**
 * Implements hook_enable().
 */
function restaurant_demo_enable() {
  Migration::registerMigration('RestaurantDemoMigratePageBanner');
  Migration::registerMigration('RestaurantDemoMigrateTexts');
}

/**
 * Implements hook_disable().
 */
function restaurant_demo_disable() {
  Migration::deregisterMigration('RestaurantDemoMigratePageBanner');
  Migration::deregisterMigration('RestaurantDemoMigrateTexts');
}
