<?php
/**
 * @file
 * Code for the Restaurant Event feature.
 */

include_once 'restaurant_event.features.inc';
include_once 'restaurant_event.theme.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */ 
function restaurant_event_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/**
 * Implements hook_menu().
 */
function restaurant_event_menu() {
  $items['admin/events/manage'] = array(
    'title' => 'Manage events',
    'weight' => 10,
    'page callback' => 'restaurant_event_manage_events_admin',
    'access arguments' => array('administer events'),
    'file' => 'restaurant_event.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/events/add'] = array(
    'title' => 'Add event',
    'weight' => 20,
    'page callback' => 'restaurant_event_add_event_admin',
    'access arguments' => array('administer events'),
    'file' => 'restaurant_event.admin.inc',
    'type' => MENU_LOCAL_ACTION,
  );

  $items['admin/events/categories'] = array(
    'title' => 'Event categories',
    'weight' => 30,
    'access arguments' => array('administer events'),
    'page callback' => 'restaurant_event_event_categories_admin',
    'file' => 'restaurant_event.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/events/categories/add'] = array(
    'title' => 'Add event category',
    'weight' => 40,
    'page callback' => 'restaurant_event_add_event_category_admin',
    'access arguments' => array('administer events'),
    'file' => 'restaurant_event.admin.inc',
    'type' => MENU_LOCAL_ACTION,
  );

  // Implement these menu items to fix notice from pm_existing_pages.
  // @see pm_existing_pages_pm_existing_pages_menu_alter.
  $items['events/calendar/day'] = array(
    'page callback' => 'restaurant_event_redirect',
    'file' => 'restaurant_event.admin.inc',
    'access callback' => FALSE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['events/calendar/month'] = array(
    'page callback' => 'restaurant_event_redirect',
    'file' => 'restaurant_event.admin.inc',
    'access callback' => FALSE,
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function restaurant_event_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  // Add action link to 'admin/events/add' on 'admin/events' page.
  $items = array(
    'actions' => array(
      'admin/events/add',
      'admin/events/categories/add',
    ),
    'tabs' => array(
      'admin/events/manage',
      'admin/events/categories',
    ),
  );
  $new_data = restaurant_admin_show_menu_items_for_paths_pattern($items, $root_path, "admin/events\nadmin/events/*");
  if (count($new_data)) {
    $data = $new_data;
  }
}

/**
 * Implements hook_permission().
 */
function restaurant_event_permission() {
  return array(
    'administer events' => array(
      'title' => t('Administer events'),
      'description' => t('Access the event admininstration pages and manage events.'),
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function restaurant_event_form_event_node_form_alter(&$form, &$form_state, $form_id) {
  // Hide the featured image field.
  $form['field_event_featured_image']['#access'] = FALSE;
}

/**
 * Implements hook_migrate_api().
 */
function restaurant_event_migrate_api() {
  return array(
    'api' => 2,
    'field handlers' => array(
      'DateMigrateFieldHandler',
    ),
    'groups' => array(
      'restaurant_event_demo' => array(
        'title' => t('Restaurant Event demo content'),
      ),
    ),
    'migrations' => restaurant_event_get_migrations(),
  );
}

/**
 * Returns an array of migrations.
 */
function restaurant_event_get_migrations() {
  return array(
    'RestaurantEventMigrateEventMigration' => array(
      'class_name' => 'RestaurantEventMigrateEventMigration',
      'group_name' => 'restaurant_event_demo',
    ),
    'RestaurantEventMigrateSlideshowMigration' => array(
      'class_name' => 'RestaurantEventMigrateSlideshowMigration',
      'group_name' => 'restaurant_event_demo',
    ),
    'RestaurantEventMigrateSlideMigration' => array(
      'class_name' => 'RestaurantEventMigrateSlideMigration',
      'group_name' => 'restaurant_event_demo',
    ),
    'RestaurantEventMigrateTextMigration' => array(
      'class_name' => 'RestaurantEventMigrateTextMigration',
      'group_name' => 'restaurant_event_demo',
    ),
  );
}
